# Site settings
title: NodeSchool Rio de Janeiro
email: antonio@milesibastos.com
description: Organizing NodeSchool events in Rio de Janeiro, RJ!
baseurl: "/rio" # the subpath of your site, e.g. /blog/
url: "http://nodeschool.io" # the base hostname & protocol for your site

twitter_username: milesibastos
github_username: milesibastos

# Build settings
markdown: kramdown
